sudo: required
services:
  - docker

before_install:
  - docker build -t azimh/docker-react -f Dockerfile.dev  .

script:
  - docker run -e CI=true azimh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReactjs-env"
  bucket_name: "elasticbeanstalk-us-west-2-812127633000"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY